# Generated by Django 5.2.4 on 2025-07-31 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('death_year', models.IntegerField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('collection_type', models.CharField(choices=[('gallery', 'Art Gallery'), ('museum', 'Museum'), ('library', 'Library'), ('archive', 'Archive'), ('digital', 'Digital Content')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curated_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('artist_name', models.CharField(help_text='Alternative to artist field for non-registered artists', max_length=200)),
                ('artwork_type', models.CharField(choices=[('painting', 'Painting'), ('sculpture', 'Sculpture'), ('photography', 'Photography'), ('digital', 'Digital Art'), ('traditional_dance', 'Traditional Dance'), ('handicraft', 'Handicraft'), ('landscape', 'Landscape'), ('historical', 'Historical Art'), ('performance', 'Performance')], max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='artworks/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnails/%Y/%m/')),
                ('year_created', models.IntegerField(blank=True, null=True)),
                ('medium', models.CharField(blank=True, max_length=200)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('cultural_significance', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='digital_repo.artist')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_artworks', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='digital_repo.category')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='digital_repo.collection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('is_virtual', models.BooleanField(default=False)),
                ('poster_image', models.ImageField(blank=True, upload_to='exhibitions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artworks', models.ManyToManyField(related_name='exhibitions', to='digital_repo.artwork')),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('visitor', 'Visitor'), ('contributor', 'Contributor'), ('curator', 'Curator'), ('admin', 'Administrator')], default='visitor', max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/')),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('email_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['category', 'is_public'], name='digital_rep_categor_4456bf_idx'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['collection', 'is_public'], name='digital_rep_collect_c4c44e_idx'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['created_at'], name='digital_rep_created_3f470d_idx'),
        ),
    ]
