# Generated by Django 5.2.4 on 2025-07-31 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_repo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='artwork',
            name='digital_rep_collect_c4c44e_idx',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='collection',
        ),
    ]
