# Generated by Django 5.2.4 on 2025-08-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_repo', '0004_museumcategory_museum_museumcollection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarydocument',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='librarydocument',
            name='subjects',
        ),
        migrations.AddField(
            model_name='librarydocument',
            name='authors',
            field=models.JSONField(blank=True, default=list, help_text='List of author names'),
        ),
        migrations.AddField(
            model_name='librarydocument',
            name='subjects',
            field=models.JSONField(blank=True, default=list, help_text='List of subject names'),
        ),
    ]
