# Generated by Django 5.2.4 on 2025-08-05 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_repo', '0005_remove_librarydocument_authors_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DigitalContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('external_url', models.URLField(help_text='Link to the external archive source')),
                ('thumbnail_url', models.URLField(blank=True, help_text='URL to thumbnail image', null=True)),
                ('source_institution', models.CharField(help_text='Institution that owns/hosts this archive', max_length=200)),
                ('date_created', models.DateField(blank=True, help_text='Original creation date of the archived material', null=True)),
                ('language', models.CharField(default='en', max_length=50)),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('private', 'Private')], default='public', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('under_review', 'Under Review')], default='active', max_length=20)),
                ('tags', models.TextField(blank=True, help_text='Comma-separated tags')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_archives', to=settings.AUTH_USER_MODEL)),
                ('archive_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='digital_repo.archivetype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DigitalContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('external_url', models.URLField(help_text='Link to the external content source')),
                ('thumbnail_url', models.URLField(blank=True, help_text='URL to thumbnail image', null=True)),
                ('source_organization', models.CharField(help_text='Organization that provides this content', max_length=200)),
                ('license', models.CharField(blank=True, help_text='License information', max_length=100)),
                ('format_type', models.CharField(blank=True, help_text='File format or content format', max_length=50)),
                ('size', models.CharField(blank=True, help_text='Size of the content (file size, dataset size, etc.)', max_length=50)),
                ('language', models.CharField(default='en', max_length=50)),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('private', 'Private')], default='public', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('under_review', 'Under Review')], default='active', max_length=20)),
                ('tags', models.TextField(blank=True, help_text='Comma-separated tags')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_digital_contents', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_contents', to='digital_repo.digitalcontenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
