# Generated by Django 5.2.4 on 2025-08-08 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_repo', '0006_archivetype_digitalcontenttype_archive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuseumArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('royal-regalia', 'Royal Regalia'), ('ceremonial-weapons', 'Ceremonial Weapons'), ('musical-instruments', 'Musical Instruments'), ('domestic-items', 'Domestic Items'), ('religious-objects', 'Religious Objects'), ('artwork', 'Artwork'), ('tools', 'Tools'), ('textiles', 'Textiles'), ('jewelry', 'Jewelry'), ('pottery', 'Pottery'), ('other', 'Other')], max_length=30)),
                ('historical_period', models.CharField(blank=True, max_length=100)),
                ('origin', models.CharField(blank=True, max_length=200)),
                ('materials', models.CharField(blank=True, help_text='Materials used to create the artifact', max_length=200)),
                ('dimensions', models.CharField(blank=True, help_text='Size/dimensions of the artifact', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='museums/artifacts/')),
                ('image_url', models.URLField(blank=True, help_text='Alternative to uploaded image')),
                ('is_on_display', models.BooleanField(default=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('acquisition_method', models.CharField(blank=True, help_text='How the artifact was acquired', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('museum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='digital_repo.museum')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MuseumGalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='museums/gallery/')),
                ('image_url', models.URLField(blank=True, help_text='Alternative to uploaded image')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('museum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='digital_repo.museum')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MuseumInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.CharField(default='9:00 AM - 5:00 PM', max_length=200)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('admission', models.TextField(blank=True, help_text='Admission pricing and details')),
                ('facilities', models.JSONField(default=list, help_text='List of available facilities')),
                ('directions', models.TextField(blank=True, help_text='Directions to the museum')),
                ('parking_info', models.TextField(blank=True)),
                ('accessibility_info', models.TextField(blank=True)),
                ('group_booking_info', models.TextField(blank=True)),
                ('special_programs', models.JSONField(default=list, help_text='List of special programs offered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('museum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_info', to='digital_repo.museum')),
            ],
            options={
                'verbose_name': 'Museum Additional Information',
                'verbose_name_plural': 'Museum Additional Information',
            },
        ),
        migrations.CreateModel(
            name='MuseumVirtualExhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('exhibition_type', models.CharField(choices=[('tour', 'Virtual Tour'), ('experience', '360° Experience'), ('exhibition', 'Digital Exhibition'), ('interactive', 'Interactive Experience'), ('documentary', 'Documentary'), ('audio-guide', 'Audio Guide')], max_length=20)),
                ('url', models.URLField(help_text='URL to the virtual exhibition/experience')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='museums/virtual_exhibitions/')),
                ('thumbnail_url', models.URLField(blank=True, help_text='Alternative to uploaded thumbnail')),
                ('duration', models.CharField(blank=True, help_text="Estimated duration (e.g., '45 minutes')", max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_registration', models.BooleanField(default=False)),
                ('access_instructions', models.TextField(blank=True, help_text='Instructions for accessing the virtual exhibition')),
                ('technical_requirements', models.TextField(blank=True, help_text='Technical requirements (VR headset, etc.)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('museum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_exhibitions', to='digital_repo.museum')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MuseumSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('overview', 'Overview'), ('cultural-heritage', 'Cultural Heritage'), ('natural-history', 'Natural History'), ('history', 'History'), ('exhibitions', 'Exhibitions'), ('custom', 'Custom Section')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.JSONField(default=list, help_text='List of content paragraphs')),
                ('subsections', models.JSONField(blank=True, default=list, help_text='List of subsection objects')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('museum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='digital_repo.museum')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'unique_together': {('museum', 'section_type')},
            },
        ),
    ]
